/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'gh-canvas':   '#f6f8fa',
        'gh-default':  '#ffffff',
        'gh-subtle':   '#f6f8fa',
        'gh-muted':    '#eaeef2',
        'gh-border':   '#d0d7de',
        'gh-blue':     '#0969da',
        'gh-blue-hover': '#0550ae',
        'gh-text':     '#1f2328',
        'gh-text-sec': '#57606a',
        'gh-text-mut': '#6e7781',
        'gh-green':    '#1a7f37',
        'gh-red':      '#cf222e',
        'gh-amber':    '#9a6700',
      },
      fontFamily: {
        sans:    ['-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', '"Noto Sans"', 'Helvetica', 'Arial', 'sans-serif'],
        display: ['-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Helvetica', 'Arial', 'sans-serif'],
        mono:    ['ui-monospace', 'SFMono-Regular', '"SF Mono"', 'Menlo', 'Consolas', '"Liberation Mono"', 'monospace'],
      },
      borderRadius: {
        none:    '0',
        sm:      '3px',
        DEFAULT: '6px',
        md:      '6px',
        lg:      '8px',
        xl:      '12px',
        '2xl':   '16px',
        full:    '9999px',
      },
      boxShadow: {
        sm:      '0 1px 0 rgba(31,35,40,0.04)',
        DEFAULT: '0 1px 0 rgba(31,35,40,0.04)',
        md:      '0 3px 6px rgba(140,149,159,0.15)',
        lg:      '0 8px 24px rgba(140,149,159,0.20)',
        modal:   '0 1px 3px rgba(31,35,40,0.12), 0 8px 24px rgba(66,74,83,0.12)',
        card:    '0 1px 0 rgba(31,35,40,0.04)',
        input:   '0 1px 0 rgba(31,35,40,0.04)',
        focus:   '0 0 0 3px rgba(9,105,218,0.3)',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up':   { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fade-in':  { from: { opacity: '0', transform: 'translateY(4px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slide-in': { from: { opacity: '0', transform: 'translateX(-6px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        'blink':    { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.3' } },
        'perm-glow':{ '0%,100%': { opacity: '0.7' }, '50%': { opacity: '1' } },
        'shake':    { '0%': { transform: 'translateX(0)' }, '15%': { transform: 'translateX(-4px)' }, '30%': { transform: 'translateX(4px)' }, '45%': { transform: 'translateX(-4px)' }, '60%': { transform: 'translateX(4px)' }, '100%': { transform: 'translateX(0)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
        'fade-in':   'fade-in 0.2s ease-out',
        'slide-in':  'slide-in 0.2s ease-out',
        'blink':     'blink 1.5s ease-in-out infinite',
        'perm-glow': 'perm-glow 2s ease-in-out infinite',
        'shake':     'shake 0.4s ease-in-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}